Revert "prima: disable SAE by default"
This need to be disable after latest CAF Tag update for prima wlan.

Current error log:
../drivers/staging/prima/CORE/MAC/src/pe/lim/limProcessAssocReqFrame.c:1553:33: error: use of undeclared identifier 'ANI_AKM_TYPE_SAE'; did you mean 'ANI_AKM_TYPE_OWE'?
                if (akm_type == ANI_AKM_TYPE_SAE) {
                                ^~~~~~~~~~~~~~~~
                                ANI_AKM_TYPE_OWE
../drivers/staging/prima/CORE/MAC/inc/aniSystemDefs.h:115:5: note: 'ANI_AKM_TYPE_OWE' declared here
    ANI_AKM_TYPE_OWE,
    ^
1 error generated

ANI_AKM_TYPE_SAE is actually part of SAE declaration..

This reverts commit e30f89033aec59fc2f651e46ec916acb75fe6975.